version: '3'

services:
  db_deploy:
    container_name: db_deploy
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm_db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_HOST=localhost

    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./backups:/home/backups
    command: -p 5433
    healthcheck:
      test: pg_isready -U postgres -p 5433
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  back:
    restart: always
    container_name: back
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db_deploy:
        condition: service_healthy